### ISSUE TITLE
Misuses of cryptographic APIs

### ISSUE THREAD

**Issue by mhp0rtal** [carlspring/maven-commons#24]
Hi
The following lines have cryptographic API misuses. <br> File name => src/main/java/org/carlspring/maven/commons/util/ChecksumUtils.java: Line number => 74: API name => MessageDigest:<BR> File name => src/main/java/org/carlspring/maven/commons/util/ChecksumUtils.java: Line number => 52: API name => MessageDigest:First parameter (with value "MD5") should be any of {SHA-256, SHA-384, SHA-512}<BR>

**Comment by carlspring** [comment]
When you write a bot, or automated tool like this, you might at least make the issue formatted using Markdown.

What exactly are you suggesting with this?

**Comment by steve-todorov** [comment]
Hi @mhp0rtal,

It's great that you have written a bot to analyze repositories and rise awareness of the issues `md5` hashing algorithm has. Fortunately, we are already aware of them. 

However the current use case has nothing to do with the implied issue. We are not storing any passwords in `md5`, which is indeed a very bad practice (not to mention all of the `md5` rainbow tables available on the net, which contain billions of hashed passwords to compare against to in seconds). 
Our code is being used for [`generating verification hashes`](https://en.wikipedia.org/wiki/File_verification) for files so that you can verify the downloaded file/dependency. I don't see how this is a problem.

Unfortunately, `md5` checksums are still heavily used by a lot of people and tools so it won't become obsolete/deprecated overnight or any time soon (specially for maven dependencies). 
At this particular time, I don't see anything we can do here as it will break a lot of tools in the chain which are out of our control/reach. 

@carlspring I believe we can close this issue as there is nothing we can do about it. :)

**Comment by carlspring** [comment]
Won't fix.

**Comment by carlspring** [comment]
@mhp0rtal ,

It would probably be more helpful, if you ran this tool against our projects in the [strongbox](https://github.com/strongbox/) organization, perhaps more notably in the [strongbox](https://github.com/strongbox/strongbox) project, where we have a significantly larger code and developer base.  The `maven-commons` project is quite-likely not used by anybody, but ourselves and we've pretty much moved away from it as well.
